# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
version: "3.8"

services:

  superlink:
    image: moon-fl-server:latest
    ports:
      - "9091:9091"
      - "9093:9093"
    restart: unless-stopped

  mlflow:
    image: ghcr.io/mlflow/mlflow:2.13.0
    ports:
      - "5000:5000"
    restart: unless-stopped
    command: mlflow server --host 0.0.0.0 --port 5000
    volumes:
      - mlflow_data:/mlflow

  supernode-0:
    image: moon-fl-client:latest
    depends_on:
      - superlink
    environment:
      - SUPERLINK_URL=superlink:9091
      - DATA_PATH=/data/client_0
    volumes:
      - /home/priyan/data/client_0:/data/client_0    # ← fixed

  supernode-1:
    image: moon-fl-client:latest
    depends_on:
      - superlink
    environment:
      - SUPERLINK_URL=superlink:9091
      - DATA_PATH=/data/client_1
    volumes:
      - /home/priyan/data/client_1:/data/client_1    # ← fixed

volumes:
  mlflow_data: