FROM pytorch/pytorch:2.3.1-cuda12.1-cudnn8-runtime

WORKDIR /app

RUN apt-get update && apt-get install -y curl \
    && rm -rf /var/lib/apt/lists/* \
    && curl -Ls https://astral.sh/uv/install.sh | sh

ENV PATH="/root/.local/bin:$PATH"

COPY .python-version pyproject.toml uv.lock ./
RUN uv sync --frozen --no-install-project --extra client --no-cache

COPY moon_fl/ ./moon_fl/
RUN uv sync --frozen --extra client --no-cache

ENV PATH="/app/.venv/bin:$PATH"
ENV SUPERLINK_URL=localhost:9091
ENV DATA_PATH=./data

CMD ["sh", "-c", "flower-supernode --insecure --superlink $SUPERLINK_URL --node-config 'data-path=\"$DATA_PATH\"'"]