FROM ghcr.io/astral-sh/uv:python3.11-slim

WORKDIR /app

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-install-project --extra server --no-cache

COPY moon_fl/ ./moon_fl/
RUN uv sync --frozen --extra server --no-cache

EXPOSE 9091 9093

CMD ["flwr-superlink", "--insecure"]