###############################################################################
# TLS Private Key — generated by Terraform, stored in S3
###############################################################################

resource "tls_private_key" "fl_server" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "fl_server" {
  key_name   = var.key_pair_name
  public_key = tls_private_key.fl_server.public_key_openssh

  tags = {
    Name    = var.key_pair_name
    Project = "MOON-FL"
  }
}

# Store private key in S3 — download once to SSH into the instance
resource "aws_s3_object" "fl_server_private_key" {
  bucket  = aws_s3_bucket.fl_checkpoints.bucket
  key     = "keys/${var.key_pair_name}.pem"
  content = tls_private_key.fl_server.private_key_pem

  server_side_encryption = "AES256"

  tags = {
    Project = "MOON-FL"
  }
}

###############################################################################
# After apply, download the key:
#   aws s3 cp s3://moon-fl-checkpoints/keys/moon-fl-key.pem ~/.ssh/moon-fl-key.pem
#   chmod 400 ~/.ssh/moon-fl-key.pem
#   ssh -i ~/.ssh/moon-fl-key.pem ubuntu@<fl_server_public_ip>
###############################################################################
